### ISSUE TITLE
Annotations not updating

### ISSUE THREAD

**Issue by Mokey2002** [Lattice-Automation/seqviz#92] opened 2021-02-16 22:45 UTC
annotations are not updating when doing test.setState();

My code:
	<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/regenerator-runtime@0.13.3/runtime.min.js"></script>
    <script type="text/javascript" src="https://unpkg.com/seqviz"></script>

var test = window.seqviz
    .Viewer("root", {
      name:"test123",
      seq: "aaaaaagggggggggggggggggggccccccccccccttttttttttttt",
      showIndex: true,
      showComplement:true,
      viewer:"both",
      style: { height: "100vh", width: "80vw"},
      annotations: [{  start: 0, end: 22, name: "Strong promoter", direction: 1 }],
    });

test.setState({
      name:"test123",
      seq: "aaaaaagggggggggggggggggggccccccccccccttttttttttttt",
      showIndex: true,
      showComplement:true,
      viewer:"both",
      style: { height: "100vh", width: "80vw"},
      //annotations: ann,
      annotations: [{  start: 0, end: 10, name: "Strong promoter", direction: 1 }],
    });

The annotation does not change, it stays from 0 to 22. It was working last week and I haven't change any of the code since last week

**Comment by jjti** [comment] 2021-02-17 14:30
this might be related to a recent change, I'll try to check it out soonish

**Comment by jjti** [comment] 2021-02-18 04:18
I believe this is fixed in the latest release `3.0.30`, just pushed. I replicated with below. It was related to a different recent fix I made to annotations.

```
// let viewer = window.seqviz.Viewer("app-root", viewerInput);
let viewer = Viewer("root", viewerInput);
viewer.render();

setTimeout(() => {
  viewer.setState({
    annotations: [{start: 1, end: 7, color: "red", name: "test"}]
  })
}, 1250)
```

**Comment by jjti** [comment] 2021-02-18 04:18
closing because I think it's fixed, but feel free to message if I'm wrong

**Comment by Mokey2002** [comment] 2021-02-18 04:55
@JJTimmons works great! thanks!

**Comment by jjti** [comment] 2021-02-18 05:01
Nice! please star the repo and tell all your friends and family about it

**Comment by Mokey2002** [comment] 2021-02-18 05:06
Will do!

**Comment by Mokey2002** [comment] 2021-03-04 04:41
@JJTimmons  I noticed another bug. The plasmid map and sequence does not update if an annotation is deleted or if it has changed the start or end.
For example:
viewerInput={ name: "L09136",
      seq: "tcgcgcgtttcggtgatgacggtgaaaacctctgacacatgca",
      style: { height: "100vh", width: "100vw" },
      annotations: [{start: 5, end: 10, color: "red", name: "test"}];
};
let viewer = Viewer("root", viewerInput);
viewer.render();

If I try to change the values of an already exiting annotation with this:
setTimeout(() => {
  viewer.setState({
    annotations: [{start: 1, end: 7, color: "red", name: "test"}]
  })
}, 1250)

The plasmid map and the sequence stays the same, with the old annotation ({start: 1, end: 10, color: "red", name: "test"})

**Comment by jjti** [comment] 2021-03-05 00:48
hmm I cannot replicate this one. I run with the below, and it updates as expected after a second. Can you check which version of seqviz you have?

```
const viewerInput = {
  name: "L09136",
seq: "tcgcgcgtttcggtgatgacggtgaaaacctctgacacatgca",
style: { height: "100vh", width: "100vw" },
annotations: [{start: 5, end: 10, color: "red", name: "test"}]
}

// let viewer = window.seqviz.Viewer("app-root", viewerInput);
let viewer = Viewer("root", viewerInput);
viewer.render();

setTimeout(() => {
  viewer.setState({
  annotations: [{start: 1, end: 7, color: "red", name: "test"}]
  })
  }, 1250)
```

I do notice that you have an extra semicolon after the annotations array, but I can't see how it would render if the first place if that were the issue:

`"test"}];`

**Comment by Mokey2002** [comment] 2021-03-09 03:34
hmm thats weird.
I'm using version - 3.0.33

I will double check my logic again.
Its probably something on my end.

**Comment by jjti** [comment] 2021-03-12 22:32
let me know! Happy to try again to reproduce w/ another test example. Closing for now for bookkeeping

**Closed as completed by jjti** 2021-03-12 22:32 UTC
